---
title: "R Notebook"
output: html_notebook
---

```{r}
#1. ¿Cómo generaría un arreglo aleatorio de 250 elementos con los colores primarios? 

colores = c("rojo", "amarillo", "azul")
arreglo = sample(colores, 250, replace = TRUE)
print(arreglo)
```

```{r}
#2. Dado un arreglo de 120000 elementos de números enteros entre 40 y 70, ¿Cómo haría para obtener la desviación estándar de aquellos números que son mayores a 55 y menores a 64?

arreglo2 = sample(40:70, 120000, replace = TRUE)
arreglo2.filtro = arreglo2[arreglo2 > 55 & arreglo2 < 64]
desviacion_estandar = sd(arreglo2.filtro)

print(desviacion_estandar)
```

```{r}
#3. Suponga que se almacena en una variable un arreglo con todos los números de carnet de los estudiantes del Instituto de Investigación de Operaciones de la universidad en forma de string, los carnets tiene al inicio dos caracteres que identifican el año en el que la persona entró a la universidad por ejemplo: 19004528 hacer referencia a una persona que ingreso en el año 2019, 06009878 hace referencia a una persona que ingreso que el año 2006, ¿Cómo haría para contar la cantidad de alumnos por año? 

carnets = c("23004069", "19004528", "06009878", "23001234", "20004321")
Carnets.yy = substr(carnets, 1, 2)

conteo = table(Carnets.yy)
print(conteo)
```

```{r}
#4. Define el vector y = (1, 3, 5, 7) utilizando la función c(). ¿Cómo lo harías con la función seq()? 
y = c(1, 3, 5, 7)
print(y)

y.2 = seq(1, 7, 2)
print(y.2)
```

```{r}
#5. Si b <- list(a=1:10, c="Hola", d="XX"), escriba una expresión en R que devuelva todos los elementos de la lista excepto los elementos 4,6,7,8 del vector a. 

b = list(a=1:10, c="hola", d="XX")
print(b$a[-c(4,6,7,8)])
```

```{r}
#6. Dado los siguientes vectores, muestre el código en R necesario para declarar y calcular el promedio, desviación estándar, mediana, moda y sumatoria total para los siguientes vectores:

#a. x=(8,7,6,5)
#b. y = (3,3, 3, 3, 3, 3, 3, 3, 2, 2)
#c. z = (1, 1.75, 2.5, 3.25, 4) 

x = c(8,7,6,5)
y = c(3,3, 3, 3, 3, 3, 3, 3, 2, 2)
z = c(1, 1.75, 2.5, 3.25, 4) 

moda = function(a) {
   return(as.numeric(names(which.max(table(a)))))
}

#Estadísticas vector x
cat("Vector x: ", x, "\n")
cat("Promedio:", mean(x), "\n")
cat("Desviación estándar:", sd(x), "\n")
cat("Mediana:", median(x), "\n")
cat("Moda:", moda(x), "\n")
cat("Sumatoria total:", sum(x), "\n\n")

#Estadísticas vector y
cat("Vector y: ", y, "\n")
cat("Promedio:", mean(y), "\n")
cat("Desviación estándar:", sd(y), "\n")
cat("Mediana:", median(y), "\n")
cat("Moda:", moda(y), "\n")
cat("Sumatoria total:", sum(y), "\n\n")

#Estadísticas vector z
cat("Vector z: ", z, "\n")
cat("Promedio:", mean(z), "\n")
cat("Desviación estándar:", sd(z), "\n")
cat("Mediana:", median(z), "\n")
cat("Moda:", moda(z), "\n")
cat("Sumatoria total:", sum(z), "\n\n")
```

```{r}
#7. Sabemos que para sumar vectores estos deben tener la misma longitud. Sin embargo R trabaja de manera distinta. Defina los vectores x = (1, 2, 3, 4, 5, 6), y = (7, 8), z = (9, 10, 11, 12). Calcula:

x = c(1, 2, 3, 4, 5, 6)
y = c(7, 8)
z = c(9, 10, 11, 12)

#a. x + x
r.1 = x+x
print(r.1)
#b. x + y.
r.2 = x+y
print(r.2)
#c. Responda ¿Qué ha hecho R? 
##R ha sumado los valores de los indices de cada registro, como una suma cartesiana.
```

```{r}
#8. Dada la variable string <- "Hola Mundo", escriba una instrucción en R que devuelva la siguiente salida:
#[[1]]
#[1] "Hola"
#[[2]]
#[1] "Mundo"

string = "Hola Mundo"
string.2 = strsplit(string, " ")[[1]]
resultado = list()
resultado[[1]] = string.2[1]
resultado[[2]] = string.2[2]

print(resultado)
```

